/**
 * Agate TypeScript SDK
 *
 * Auto-generated client from OpenAPI spec.
 * Do not edit this file manually - it will be regenerated.
 */

// Re-export everything from the generated client
export * from './gen/index.js';
export * from './gen/types.gen.js';
