package session

import (
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"agate/internal/debug"
	"agate/pkg/agents"
	"agate/pkg/config"
	"agate/pkg/git"
	"agate/pkg/telemetry"
	"agate/pkg/tmux"
)

// Manager is a singleton that manages all multi-agent sessions
type Manager struct {
	agentSessions map[string]*Session      // SessionID -> multi-agent Session
	activeSession *Session                 // Currently active session
	repositories  map[string]*git.Repository // Repo name -> git Repository (shared across sessions)
	stateMgr      StateManager             // Thread-safe state persistence
	mu            sync.RWMutex             // Protects concurrent access
}

// StateManager defines the interface for state persistence
type StateManager interface {
	SaveSessionMapping(sessionID string, session config.PersistedSession) error
	RemoveSessionMapping(sessionID string) error
	GetSessionMappings() map[string]config.PersistedSession
	GetPinnedSessions() []string
	UpdateSessions(fn func(*config.SessionState) error) error
	GetLastWorktreeForRepo(repoName string) *config.WorktreeRef
}

// NewManager creates a new session manager
func NewManager(stateMgr StateManager) *Manager {
	if stateMgr == nil {
		debug.DebugLog("WARNING: SessionManager created with nil StateManager - persistence will not work")
	}

	mgr := &Manager{
		agentSessions: make(map[string]*Session),
		repositories:  make(map[string]*git.Repository),
		stateMgr:      stateMgr,
	}

	// Create repository for current working directory
	repo, err := git.NewRepository()
	if err != nil {
		debug.DebugLog("WARNING: Failed to initialize repository: %v - sessions cannot be created", err)
	} else {
		repoName := repo.GetRepositoryName()
		mgr.repositories[repoName] = repo
	}

	return mgr
}

// getRepository returns the Repository for the current working directory (launch repo)
// Returns error if no repository is available
func (m *Manager) getRepository() (*git.Repository, error) {
	// Get the first (and typically only) repository from the map
	// This is the repository we were launched from
	for _, repo := range m.repositories {
		return repo, nil
	}
	return nil, fmt.Errorf("no repository available - not in a git repository")
}

// getRepositoryByName returns a Repository for the given repo name, creating it if needed
func (m *Manager) getRepositoryByName(repoName string) (*git.Repository, error) {
	if repo, ok := m.repositories[repoName]; ok {
		return repo, nil
	}

	// Repository doesn't exist yet - would need to be created from a path
	// For now, return error (this will be used when restoring sessions from other repos)
	return nil, fmt.Errorf("repository not found: %s", repoName)
}

// CreateSession creates a new multi-agent session
// branchName is already generated by the caller
// agentNames is the list of agents to create instances for
// CreateSession creates a new session with default terminal size
func (m *Manager) CreateSession(prompt string, branchName string, agentNames []string) (*Session, error) {
	return m.CreateSessionWithSize(prompt, branchName, agentNames, 200, 50)
}

// CreateSessionWithSize creates a new session with specified terminal dimensions
func (m *Manager) CreateSessionWithSize(prompt string, branchName string, agentNames []string, termWidth, termHeight int) (*Session, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	debug.DebugLog("CreateSession: Starting session creation with prompt='%s', branch='%s', agents=%v, size=%dx%d", prompt, branchName, agentNames, termWidth, termHeight)

	if len(agentNames) == 0 {
		return nil, fmt.Errorf("at least one agent must be specified")
	}

	// Generate session ID
	sessionID := fmt.Sprintf("session_%d", time.Now().UnixNano())
	debug.DebugLog("CreateSession: Generated sessionID=%s", sessionID)

	// Create session object
	session := &Session{
		ID:               sessionID,
		Prompt:           prompt,
		Description:      "", // Empty initially, populated async
		BranchBaseName:   branchName,
		Agents:           make(map[string]*Agent),
		ActiveAgentIndex: 0,
		CreatedAt:        time.Now(),
		LastAccessed:     time.Now(),
		TermWidth:        termWidth,
		TermHeight:       termHeight,
	}

	// Get pane layout to determine correct pane indices
	layout := tmux.CalculatePaneLayout(len(agentNames))

	// Create all agents concurrently (just worktrees, no tmux yet)
	type agentResult struct {
		agentName string
		agent     *Agent
		err       error
	}

	results := make(chan agentResult, len(agentNames))
	var wg sync.WaitGroup

	for i, agentName := range agentNames {
		wg.Add(1)
		go func(name string, paneIndex int) {
			defer wg.Done()
			agent, err := m.createAgent(sessionID, branchName, name, paneIndex)
			results <- agentResult{agentName: name, agent: agent, err: err}
		}(agentName, layout.AgentToPaneMap[i])
	}

	// Wait for all agents to complete
	go func() {
		wg.Wait()
		close(results)
	}()

	// Collect results
	var errors []string
	for result := range results {
		if result.err != nil {
			errors = append(errors, fmt.Sprintf("%s: %v", result.agentName, result.err))
			continue
		}
		session.Agents[result.agentName] = result.agent
	}

	if len(errors) > 0 {
		// Clean up any successfully created agents
		for _, agent := range session.Agents {
			m.cleanupAgent(agent)
		}
		return nil, fmt.Errorf("failed to create agents: %s", strings.Join(errors, "; "))
	}

	if len(session.Agents) == 0 {
		return nil, fmt.Errorf("no agents were created")
	}

	// Now create the shared tmux session with all agents
	if err := m.setupTmuxSession(session); err != nil {
		// Clean up all agents on failure
		for _, agent := range session.Agents {
			m.cleanupAgent(agent)
		}
		return nil, fmt.Errorf("failed to setup tmux session: %w", err)
	}

	// Store session
	m.agentSessions[sessionID] = session

	// Set as active session so TUI will show it
	m.activeSession = session

	// Persist session with active state
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist new session %s: %v", sessionID, err)
	}

	// Track session creation
	isFirstSession := len(m.agentSessions) == 1
	telemetry.TrackPromptEntered(prompt, agentNames)
	telemetry.TrackAgentsSelected(agentNames)
	telemetry.TrackSessionCreated(agentNames, isFirstSession)

	debug.DebugLog("Created new multi-agent session: %s with %d agents", sessionID, len(session.Agents))
	return session, nil
}

// createAgent creates a single agent for a session (worktree only, no tmux)
func (m *Manager) createAgent(sessionID string, branchName string, agentName string, paneIndex int) (*Agent, error) {
	debug.DebugLog("createAgent: Creating agent=%s, baseBranch=%s, sessionID=%s, paneIndex=%d", agentName, branchName, sessionID, paneIndex)

	// Get agent configuration
	agentConfig := agents.GetAgentConfig(agentName)

	// Get repository for creating worktree
	repo, err := m.getRepository()
	if err != nil {
		return nil, fmt.Errorf("failed to get repository: %w", err)
	}

	// Create worktree for this agent
	// For multi-agent sessions, append agent name to branch to make it unique
	agentBranchName := fmt.Sprintf("%s_%s", branchName, agentName)
	debug.DebugLog("createAgent: Creating worktree with unique branch=%s for agent=%s", agentBranchName, agentName)

	worktree, err := repo.CreateWorktree(agentBranchName)
	if err != nil {
		debug.DebugLog("createAgent: Failed to create worktree for agent=%s, branch=%s: %v", agentName, agentBranchName, err)
		return nil, fmt.Errorf("failed to create worktree: %w", err)
	}
	debug.DebugLog("createAgent: Successfully created worktree at %s for agent=%s", worktree.Path, agentName)

	// Generate agent ID
	agentID := fmt.Sprintf("%s_%s", sessionID, agentName)

	agent := &Agent{
		ID:           agentID,
		AgentConfig:  agentConfig,
		SessionID:    sessionID,
		Worktree:     worktree,
		PaneIndex:    paneIndex,
		CreatedAt:    time.Now(),
		LastAccessed: time.Now(),
	}

	return agent, nil
}

// setupTmuxSession creates a single tmux session with panes for all agents
func (m *Manager) setupTmuxSession(session *Session) error {
	debug.DebugLog("setupTmuxSession: Creating shared tmux session for %d agents", len(session.Agents))

	// Get ordered list of agents
	sessionAgents := session.GetOrderedAgents()
	if len(sessionAgents) == 0 {
		return fmt.Errorf("no agents in session")
	}

	// Use the first agent's worktree to generate the tmux session name
	// (all agents share one tmux session now)
	tmuxSessionName := generateTmuxSessionName(sessionAgents[0].Worktree, session.BranchBaseName)

	// Create the tmux session (don't launch agent yet - we'll send commands via send-keys)
	// Session starts with a shell prompt so we can send agent commands via send-keys
	tmuxSession := tmux.NewTmuxSession(tmuxSessionName)
	err := tmuxSession.Start(sessionAgents[0].Worktree.Path)
	if err != nil {
		return fmt.Errorf("failed to start tmux session: %w", err)
	}

	// Store tmux session in the Session
	session.SharedTmux = tmuxSession

	// Resize tmux window to match user's terminal dimensions BEFORE creating panes
	// This ensures agents detect the correct terminal width on startup
	resizeCmd := tmux.Command("resize-window", "-t", tmuxSessionName, "-x", fmt.Sprintf("%d", session.TermWidth), "-y", fmt.Sprintf("%d", session.TermHeight))
	if err := resizeCmd.Run(); err != nil {
		debug.DebugLog("setupTmuxSession: Warning - failed to resize window: %v", err)
	} else {
		debug.DebugLog("setupTmuxSession: Resized window to %dx%d before creating panes", session.TermWidth, session.TermHeight)
	}

	// Build agent configs and worktrees in order
	agentConfigs := make([]agents.AgentConfig, len(sessionAgents))
	worktrees := make([]*git.WorktreeInfo, len(sessionAgents))
	for i, agent := range sessionAgents {
		agentConfigs[i] = agent.AgentConfig
		worktrees[i] = agent.Worktree
	}

	// Create panes and start agents with prompts
	// Agents are launched with prompts as CLI arguments, so they start immediately
	if err := tmux.CreatePanes(tmuxSessionName, agentConfigs, worktrees, session.ID, session.Prompt); err != nil {
		// Kill the tmux session on failure
		tmuxSession.Kill()
		return fmt.Errorf("failed to create panes: %w", err)
	}

	// Handle post-launch actions for Claude only (trust prompt handling)
	// Other agents don't need any post-launch handling since they launched with prompts
	// Run in background - don't block session creation
	go func() {
		var wg sync.WaitGroup
		for _, agent := range sessionAgents {
			wg.Add(1)
			go func(a *Agent) {
				defer wg.Done()
				if err := a.AgentConfig.HandlePostLaunch(tmuxSessionName, a.PaneIndex, session.Prompt); err != nil {
					debug.DebugLog("setupTmuxSession: Warning - post-launch failed for %s: %v", a.AgentConfig.Name, err)
					// Don't fail the session - post-launch is best-effort
				} else {
					debug.DebugLog("setupTmuxSession: Agent %s post-launch complete in pane %d", a.AgentConfig.Name, a.PaneIndex)
				}
			}(agent)
		}
		wg.Wait()
		debug.DebugLog("setupTmuxSession: All post-launch handlers complete")
	}()

	// Create metrics pane immediately (no longer using hook since we have terminal dimensions at launch)
	debug.DebugLog("[ISSUE2] Creating metrics pane directly for session %s", tmuxSessionName)
	if err := tmux.CreateMetricsPane(tmuxSessionName, session.ID); err != nil {
		debug.DebugLog("[ISSUE2] Warning - failed to create metrics pane: %v", err)
		// Don't fail - metrics is optional
	} else {
		debug.DebugLog("[ISSUE2] Successfully created metrics pane")
	}

	// Focus the first agent's pane to match ActiveAgentIndex = 0
	// This ensures CapturePaneContent() captures the correct agent at launch
	if err := tmux.SelectPane(tmuxSessionName, sessionAgents[0].PaneIndex); err != nil {
		debug.DebugLog("Warning: failed to select first agent's pane: %v", err)
		// Don't fail - this is just for UI consistency
	}

	debug.DebugLog("setupTmuxSession: Successfully created tmux session with %d panes + metrics", len(sessionAgents))
	return nil
}

// cleanupAgent cleans up resources for an agent
func (m *Manager) cleanupAgent(agent *Agent) {
	if agent.Worktree != nil {
		repo, err := m.getRepository()
		if err != nil {
			debug.DebugLog("Failed to get repository for cleanup: %v", err)
			return
		}
		if err := repo.DeleteWorktree(*agent.Worktree); err != nil {
			debug.DebugLog("Failed to delete worktree for agent %s: %v", agent.ID, err)
		}
	}
}

// UpdateSessionDescription updates the description after async generation
func (m *Manager) UpdateSessionDescription(sessionID string, description string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.agentSessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	session.Description = description
	session.LastAccessed = time.Now()

	// Persist the update
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist description update for session %s: %v", sessionID, err)
		return err
	}

	debug.DebugLog("Updated description for session %s", sessionID)
	return nil
}

// AddAgentToSession adds a new agent to an existing session
// TODO: This needs to be reworked for shared tmux sessions - need to recreate panes
func (m *Manager) AddAgentToSession(sessionID string, agentName string) (*Agent, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.agentSessions[sessionID]
	if !exists {
		return nil, fmt.Errorf("session not found: %s", sessionID)
	}

	// Check if agent already exists in this session
	if _, exists := session.Agents[agentName]; exists {
		return nil, fmt.Errorf("agent %s already exists in session %s", agentName, sessionID)
	}

	// Check if we've hit the limit
	if len(session.Agents) >= 6 {
		return nil, fmt.Errorf("maximum 6 agents per session, cannot add more")
	}

	// Create the new agent (worktree only)
	paneIndex := len(session.Agents) // New agent gets the next pane index
	agent, err := m.createAgent(sessionID, session.BranchBaseName, agentName, paneIndex)
	if err != nil {
		return nil, err
	}

	session.Agents[agentName] = agent
	session.LastAccessed = time.Now()

	// TODO: Rebuild tmux panes layout with the new agent
	// For now, this function is not fully implemented for shared sessions

	// Persist the update
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist after adding agent to session %s: %v", sessionID, err)
	}

	debug.DebugLog("Added agent %s to session %s", agentName, sessionID)
	return agent, nil
}

// CycleActiveAgent increments the active agent index (wraps around) and focuses that pane
func (m *Manager) CycleActiveAgent(sessionID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.agentSessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	agents := session.GetOrderedAgents()
	if len(agents) == 0 {
		return fmt.Errorf("no agents in session")
	}

	session.ActiveAgentIndex = (session.ActiveAgentIndex + 1) % len(agents)
	session.LastAccessed = time.Now()

	// Focus the newly active agent's pane
	if session.SharedTmux != nil {
		activeAgent := agents[session.ActiveAgentIndex]
		if err := tmux.SelectPane(session.SharedTmux.GetSessionName(), activeAgent.PaneIndex); err != nil {
			debug.DebugLog("Failed to select pane %d: %v", activeAgent.PaneIndex, err)
		}
	}

	// Track agent switched
	telemetry.TrackAgentSwitched()

	debug.DebugLog("Cycled active agent for session %s to index %d", sessionID, session.ActiveAgentIndex)
	return nil
}

// SetActiveAgent sets a specific agent as active by index and focuses that pane
func (m *Manager) SetActiveAgent(sessionID string, index int) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.agentSessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	agents := session.GetOrderedAgents()
	if index < 0 || index >= len(agents) {
		return fmt.Errorf("invalid agent index: %d (valid range: 0-%d)", index, len(agents)-1)
	}

	session.ActiveAgentIndex = index
	session.LastAccessed = time.Now()

	// Focus the newly active agent's pane
	if session.SharedTmux != nil {
		activeAgent := agents[index]
		if err := tmux.SelectPane(session.SharedTmux.GetSessionName(), activeAgent.PaneIndex); err != nil {
			debug.DebugLog("Failed to select pane %d: %v", activeAgent.PaneIndex, err)
		}
	}

	debug.DebugLog("Set active instance for session %s to index %d", sessionID, index)
	return nil
}

// SwitchToSession activates the specified session
func (m *Manager) SwitchToSession(sessionID string) (*Session, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.agentSessions[sessionID]
	if !exists {
		return nil, fmt.Errorf("session not found: %s", sessionID)
	}

	// Update active session
	m.activeSession = session
	session.LastAccessed = time.Now()

	// Persist active session change
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist active session change: %v", err)
	}

	// Track session activation
	telemetry.TrackSessionActivated(session.Agent().Name)

	debug.DebugLog("Switched to session: %s", sessionID)
	return session, nil
}

// GetActiveSession returns the currently active session
func (m *Manager) GetActiveSession() *Session {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.activeSession
}

// DeleteSession removes and cleans up a session and all its instances
func (m *Manager) DeleteSession(sessionID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.agentSessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	debug.DebugLog("Deleting session: %s", sessionID)

	// Kill shared tmux session
	if session.SharedTmux != nil {
		if err := session.SharedTmux.Kill(); err != nil {
			debug.DebugLog("Failed to kill tmux session: %v", err)
		}
	}

	// Clean up all agents
	for agentName, agent := range session.Agents {
		debug.DebugLog("Cleaning up agent %s", agentName)
		m.cleanupAgent(agent)
	}

	// Remove from sessions map
	delete(m.agentSessions, sessionID)

	// If this was the active session, clear it
	if m.activeSession == session {
		m.activeSession = nil
	}

	// Persist changes
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist after deleting session: %v", err)
	}

	// Track session deletion
	telemetry.TrackSessionDeleted(session.Agent().Name)

	debug.DebugLog("Successfully deleted session: %s", sessionID)
	return nil
}

// ListSessions returns all sessions
func (m *Manager) ListSessions() []*Session {
	m.mu.RLock()
	defer m.mu.RUnlock()

	sessions := make([]*Session, 0, len(m.agentSessions))
	for _, session := range m.agentSessions {
		sessions = append(sessions, session)
	}
	return sessions
}

// GetRepositoryPath returns the absolute path for the given repository name
func (m *Manager) GetRepositoryPath(repoName string) (string, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	repoName = strings.TrimSpace(repoName)
	if repoName == "" {
		// Return first repository path
		for _, repo := range m.repositories {
			return repo.GetRepositoryPath(), nil
		}
		return "", fmt.Errorf("repository name cannot be empty")
	}

	// Check if we have this repository
	if repo, ok := m.repositories[repoName]; ok {
		return repo.GetRepositoryPath(), nil
	}

	// Search through sessions for a worktree with this repo name
	for _, session := range m.agentSessions {
		for _, agent := range session.Agents {
			if agent != nil && agent.Worktree != nil && agent.Worktree.RepoName == repoName {
				path := strings.TrimSpace(agent.Worktree.Path)
				if path != "" {
					return filepath.Clean(path), nil
				}
			}
		}
	}

	if m.stateMgr != nil {
		if ref := m.stateMgr.GetLastWorktreeForRepo(repoName); ref != nil {
			path := strings.TrimSpace(ref.Path)
			if path != "" {
				return filepath.Clean(path), nil
			}
		}
	}

	return "", fmt.Errorf("repository path not found for repo: %s", repoName)
}

// GetRepository returns the default repository for the launch directory
func (m *Manager) GetRepository() (*git.Repository, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	return m.getRepository()
}

// GetRepositoryForRepo returns a Repository scoped to the given repository name
func (m *Manager) GetRepositoryForRepo(repoName string) (*git.Repository, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	repoName = strings.TrimSpace(repoName)
	if repoName == "" {
		// Return first repository
		for _, repo := range m.repositories {
			return repo, nil
		}
		return nil, fmt.Errorf("repository name cannot be empty")
	}

	// Check if we already have this repository
	if repo, ok := m.repositories[repoName]; ok {
		return repo, nil
	}

	// Need to create repository from a path
	repoPath, err := m.GetRepositoryPath(repoName)
	if err != nil {
		return nil, err
	}

	repo, err := git.NewRepositoryForPath(repoPath)
	if err != nil {
		return nil, err
	}

	// Cache it
	m.repositories[repoName] = repo

	return repo, nil
}

// RestoreSessions attempts to reconnect to existing sessions on startup
func (m *Manager) RestoreSessions() error {
	return m.LoadSessions()
}

// CleanupOrphanedSessions removes sessions for tmux sessions that no longer exist
func (m *Manager) CleanupOrphanedSessions() {
	m.mu.Lock()
	defer m.mu.Unlock()

	for sessionID, session := range m.agentSessions {
		// Check if the shared tmux session still exists
		if session.SharedTmux != nil {
			exists, err := session.SharedTmux.SessionExists()
			if err != nil || !exists {
				debug.DebugLog("Removing orphaned session: %s (tmux session no longer exists)", sessionID)
				delete(m.agentSessions, sessionID)
				if m.activeSession == session {
					m.activeSession = nil
				}
			}
		}
	}
}


// GetSessionForWorktree returns the session containing an agent with the given worktree
func (m *Manager) GetSessionForWorktree(worktree *git.WorktreeInfo) *Session {
	m.mu.RLock()
	defer m.mu.RUnlock()

	if worktree == nil {
		return nil
	}

	// Search through all sessions for an agent with this worktree path
	for _, session := range m.agentSessions {
		for _, agent := range session.Agents {
			if agent != nil && agent.Worktree != nil && agent.Worktree.Path == worktree.Path {
				return session
			}
		}
	}
	return nil
}

// GetOrCreateSession is deprecated - creates a new single-agent session
// For new code, use CreateSession instead
func (m *Manager) GetOrCreateSession(worktree *git.WorktreeInfo, agentName string) (*Session, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Check if a session exists with an agent using this worktree
	for _, session := range m.agentSessions {
		for _, agent := range session.Agents {
			if agent != nil && agent.Worktree != nil && agent.Worktree.Path == worktree.Path {
				session.LastAccessed = time.Now()
				debug.DebugLog("Reusing existing session: %s for worktree %s", session.ID, worktree.Path)
				return session, nil
			}
		}
	}

	// Create a new single-agent session
	// Generate a branch name from the worktree
	branchName := worktree.Branch
	if branchName == "" {
		branchName = "unknown"
	}

	// Unlock before calling CreateSession since it will lock
	m.mu.Unlock()
	session, err := m.CreateSession("", branchName, []string{agentName})
	m.mu.Lock()

	return session, err
}

