package session

import (
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"agate/internal/debug"
	"agate/pkg/app"
	"agate/pkg/config"
	"agate/pkg/git"
	"agate/pkg/tmux"
)

// Manager is a singleton that manages all multi-agent sessions
type Manager struct {
	sessions      map[string]*Session      // SessionID -> Session
	activeSession *Session                 // Currently active session
	worktreeMgr   *git.WorktreeManager     // Default Git worktree manager (launch repo)
	worktreeMap   map[string]*git.WorktreeManager
	stateMgr      StateManager             // Thread-safe state persistence
	mu            sync.RWMutex             // Protects concurrent access
}

// StateManager defines the interface for state persistence
type StateManager interface {
	SaveSessionMapping(sessionID string, session config.PersistedSession) error
	RemoveSessionMapping(sessionID string) error
	GetSessionMappings() map[string]config.PersistedSession
	SetActiveSession(sessionID string) error
	GetActiveSession() string
	GetPinnedSessions() []string
	UpdateSessions(fn func(*config.SessionState) error) error
	GetLastWorktreeForRepo(repoName string) *config.WorktreeRef
}

// NewManager creates a new session manager
func NewManager(worktreeMgr *git.WorktreeManager, stateMgr StateManager) *Manager {
	if stateMgr == nil {
		debug.DebugLog("WARNING: SessionManager created with nil StateManager - persistence will not work")
	}

	mgr := &Manager{
		sessions:    make(map[string]*Session),
		worktreeMgr: worktreeMgr,
		worktreeMap: make(map[string]*git.WorktreeManager),
		stateMgr:    stateMgr,
	}

	if worktreeMgr != nil {
		repoName := worktreeMgr.GetRepositoryName()
		mgr.worktreeMap[repoName] = worktreeMgr
	}

	return mgr
}

// CreateSession creates a new multi-agent session
// branchName is already generated by the caller
// agentNames is the list of agents to create instances for
func (m *Manager) CreateSession(prompt string, branchName string, agentNames []string) (*Session, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	debug.DebugLog("CreateSession: Starting session creation with prompt='%s', branch='%s', agents=%v", prompt, branchName, agentNames)

	if len(agentNames) == 0 {
		return nil, fmt.Errorf("at least one agent must be specified")
	}

	// Generate session ID
	sessionID := fmt.Sprintf("session_%d", time.Now().UnixNano())
	debug.DebugLog("CreateSession: Generated sessionID=%s", sessionID)

	// Create session object
	session := &Session{
		ID:                  sessionID,
		Prompt:              prompt,
		Description:         "", // Empty initially, populated async
		BranchBaseName:      branchName,
		Instances:           make(map[string]*AgentInstance),
		ActiveInstanceIndex: 0,
		CreatedAt:           time.Now(),
		LastAccessed:        time.Now(),
	}

	// Create all agent instances concurrently
	type instanceResult struct {
		agentName string
		instance  *AgentInstance
		err       error
	}

	results := make(chan instanceResult, len(agentNames))
	var wg sync.WaitGroup

	for _, agentName := range agentNames {
		wg.Add(1)
		go func(name string) {
			defer wg.Done()
			instance, err := m.createAgentInstance(sessionID, branchName, name)
			results <- instanceResult{agentName: name, instance: instance, err: err}
		}(agentName)
	}

	// Wait for all instances to complete
	go func() {
		wg.Wait()
		close(results)
	}()

	// Collect results
	var errors []string
	for result := range results {
		if result.err != nil {
			errors = append(errors, fmt.Sprintf("%s: %v", result.agentName, result.err))
			continue
		}
		session.Instances[result.agentName] = result.instance
	}

	if len(errors) > 0 {
		// Clean up any successfully created instances
		for _, instance := range session.Instances {
			m.cleanupAgentInstance(instance)
		}
		return nil, fmt.Errorf("failed to create agent instances: %s", strings.Join(errors, "; "))
	}

	if len(session.Instances) == 0 {
		return nil, fmt.Errorf("no agent instances were created")
	}

	// Store session
	m.sessions[sessionID] = session

	// Persist session
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist new session %s: %v", sessionID, err)
	}

	debug.DebugLog("Created new multi-agent session: %s with %d agents", sessionID, len(session.Instances))
	return session, nil
}

// createAgentInstance creates a single agent instance for a session
func (m *Manager) createAgentInstance(sessionID string, branchName string, agentName string) (*AgentInstance, error) {
	debug.DebugLog("createAgentInstance: Creating instance for agent=%s, baseBranch=%s, sessionID=%s", agentName, branchName, sessionID)

	// Get agent configuration
	agentConfig := app.GetAgentConfig(agentName)

	// Create worktree for this agent
	// For multi-agent sessions, append agent name to branch to make it unique
	agentBranchName := fmt.Sprintf("%s_%s", branchName, agentName)
	debug.DebugLog("createAgentInstance: Creating worktree with unique branch=%s for agent=%s", agentBranchName, agentName)

	worktree, err := m.worktreeMgr.CreateWorktree(agentBranchName)
	if err != nil {
		debug.DebugLog("createAgentInstance: Failed to create worktree for agent=%s, branch=%s: %v", agentName, agentBranchName, err)
		return nil, fmt.Errorf("failed to create worktree: %w", err)
	}
	debug.DebugLog("createAgentInstance: Successfully created worktree at %s for agent=%s", worktree.Path, agentName)

	// Generate instance ID
	instanceID := fmt.Sprintf("%s_%s", sessionID, agentName)

	// Create tmux session
	tmuxSessionName := generateTmuxSessionName(worktree, agentName)
	tmuxSession := tmux.NewTmuxSession(tmuxSessionName, agentName)
	err = tmuxSession.Start(worktree.Path)
	if err != nil {
		// Clean up worktree on failure
		m.worktreeMgr.DeleteWorktree(*worktree)
		return nil, fmt.Errorf("failed to start tmux session: %w", err)
	}

	instance := &AgentInstance{
		ID:           instanceID,
		AgentConfig:  agentConfig,
		SessionID:    sessionID,
		TmuxSession:  tmuxSession,
		Worktree:     worktree,
		CreatedAt:    time.Now(),
		LastAccessed: time.Now(),
	}

	return instance, nil
}

// cleanupAgentInstance cleans up resources for an agent instance
func (m *Manager) cleanupAgentInstance(instance *AgentInstance) {
	if instance.TmuxSession != nil {
		if err := instance.TmuxSession.Kill(); err != nil {
			debug.DebugLog("Failed to kill tmux session for instance %s: %v", instance.ID, err)
		}
	}

	if instance.Worktree != nil && m.worktreeMgr != nil {
		if err := m.worktreeMgr.DeleteWorktree(*instance.Worktree); err != nil {
			debug.DebugLog("Failed to delete worktree for instance %s: %v", instance.ID, err)
		}
	}
}

// UpdateSessionDescription updates the description after async generation
func (m *Manager) UpdateSessionDescription(sessionID string, description string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.sessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	session.Description = description
	session.LastAccessed = time.Now()

	// Persist the update
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist description update for session %s: %v", sessionID, err)
		return err
	}

	debug.DebugLog("Updated description for session %s", sessionID)
	return nil
}

// AddAgentToSession adds a new agent to an existing session
func (m *Manager) AddAgentToSession(sessionID string, agentName string) (*AgentInstance, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.sessions[sessionID]
	if !exists {
		return nil, fmt.Errorf("session not found: %s", sessionID)
	}

	// Check if agent already exists in this session
	if _, exists := session.Instances[agentName]; exists {
		return nil, fmt.Errorf("agent %s already exists in session %s", agentName, sessionID)
	}

	// Create the new agent instance
	instance, err := m.createAgentInstance(sessionID, session.BranchBaseName, agentName)
	if err != nil {
		return nil, err
	}

	session.Instances[agentName] = instance
	session.LastAccessed = time.Now()

	// Persist the update
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist after adding agent to session %s: %v", sessionID, err)
	}

	debug.DebugLog("Added agent %s to session %s", agentName, sessionID)
	return instance, nil
}

// CycleActiveInstance increments the active instance index (wraps around)
func (m *Manager) CycleActiveInstance(sessionID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.sessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	instances := session.GetOrderedInstances()
	if len(instances) == 0 {
		return fmt.Errorf("no instances in session")
	}

	session.ActiveInstanceIndex = (session.ActiveInstanceIndex + 1) % len(instances)
	session.LastAccessed = time.Now()

	debug.DebugLog("Cycled active instance for session %s to index %d", sessionID, session.ActiveInstanceIndex)
	return nil
}

// SetActiveInstance sets a specific agent as active by index
func (m *Manager) SetActiveInstance(sessionID string, index int) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.sessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	instances := session.GetOrderedInstances()
	if index < 0 || index >= len(instances) {
		return fmt.Errorf("invalid instance index: %d (valid range: 0-%d)", index, len(instances)-1)
	}

	session.ActiveInstanceIndex = index
	session.LastAccessed = time.Now()

	debug.DebugLog("Set active instance for session %s to index %d", sessionID, index)
	return nil
}

// SwitchToSession activates the specified session
func (m *Manager) SwitchToSession(sessionID string) (*Session, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.sessions[sessionID]
	if !exists {
		return nil, fmt.Errorf("session not found: %s", sessionID)
	}

	// Update active session
	m.activeSession = session
	session.LastAccessed = time.Now()

	// Persist active session change
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist active session change: %v", err)
	}

	debug.DebugLog("Switched to session: %s", sessionID)
	return session, nil
}

// GetActiveSession returns the currently active session
func (m *Manager) GetActiveSession() *Session {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.activeSession
}

// DeleteSession removes and cleans up a session and all its instances
func (m *Manager) DeleteSession(sessionID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	session, exists := m.sessions[sessionID]
	if !exists {
		return fmt.Errorf("session not found: %s", sessionID)
	}

	debug.DebugLog("Deleting session: %s", sessionID)

	// Clean up all agent instances
	for agentName, instance := range session.Instances {
		debug.DebugLog("Cleaning up instance for agent %s", agentName)
		m.cleanupAgentInstance(instance)
	}

	// Remove from sessions map
	delete(m.sessions, sessionID)

	// If this was the active session, clear it
	if m.activeSession == session {
		m.activeSession = nil
	}

	// Persist changes
	if err := m.PersistSessions(); err != nil {
		debug.DebugLog("Failed to persist after deleting session: %v", err)
	}

	debug.DebugLog("Successfully deleted session: %s", sessionID)
	return nil
}

// ListSessions returns all sessions
func (m *Manager) ListSessions() []*Session {
	m.mu.RLock()
	defer m.mu.RUnlock()

	sessions := make([]*Session, 0, len(m.sessions))
	for _, session := range m.sessions {
		sessions = append(sessions, session)
	}
	return sessions
}

// GetRepositoryPath returns the absolute path for the given repository name
func (m *Manager) GetRepositoryPath(repoName string) (string, error) {
	m.mu.RLock()
	defer m.mu.RUnlock()

	repoName = strings.TrimSpace(repoName)
	if repoName == "" {
		if m.worktreeMgr != nil {
			return m.worktreeMgr.GetRepositoryPath(), nil
		}
		return "", fmt.Errorf("repository name cannot be empty")
	}

	if manager, ok := m.worktreeMap[repoName]; ok && manager != nil {
		return manager.GetRepositoryPath(), nil
	}

	if m.worktreeMgr != nil && m.worktreeMgr.GetRepositoryName() == repoName {
		return m.worktreeMgr.GetRepositoryPath(), nil
	}

	// Search through sessions for a worktree with this repo name
	for _, session := range m.sessions {
		for _, instance := range session.Instances {
			if instance != nil && instance.Worktree != nil && instance.Worktree.RepoName == repoName {
				path := strings.TrimSpace(instance.Worktree.Path)
				if path != "" {
					return filepath.Clean(path), nil
				}
			}
		}
	}

	if m.stateMgr != nil {
		if ref := m.stateMgr.GetLastWorktreeForRepo(repoName); ref != nil {
			path := strings.TrimSpace(ref.Path)
			if path != "" {
				return filepath.Clean(path), nil
			}
		}
	}

	return "", fmt.Errorf("repository path not found for repo: %s", repoName)
}

// GetWorktreeManagerForRepo returns a worktree manager scoped to the given repository
func (m *Manager) GetWorktreeManagerForRepo(repoName string) (*git.WorktreeManager, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	repoName = strings.TrimSpace(repoName)
	if repoName == "" {
		if m.worktreeMgr != nil {
			return m.worktreeMgr, nil
		}
		return nil, fmt.Errorf("repository name cannot be empty")
	}

	if manager, ok := m.worktreeMap[repoName]; ok && manager != nil {
		return manager, nil
	}

	repoPath, err := m.GetRepositoryPath(repoName)
	if err != nil {
		return nil, err
	}

	manager, err := git.NewWorktreeManagerForPath(repoPath)
	if err != nil {
		return nil, err
	}

	if m.worktreeMap == nil {
		m.worktreeMap = make(map[string]*git.WorktreeManager)
	}
	key := manager.GetRepositoryName()
	m.worktreeMap[key] = manager
	if key != repoName {
		m.worktreeMap[repoName] = manager
	}

	return manager, nil
}

// RestoreSessions attempts to reconnect to existing sessions on startup
func (m *Manager) RestoreSessions() error {
	return m.LoadSessions()
}

// CleanupOrphanedSessions removes sessions for tmux sessions that no longer exist
func (m *Manager) CleanupOrphanedSessions() {
	m.mu.Lock()
	defer m.mu.Unlock()

	for sessionID, session := range m.sessions {
		hasValidInstances := false
		for agentName, instance := range session.Instances {
			if instance.TmuxSession != nil {
				exists, err := instance.TmuxSession.SessionExists()
				if err != nil || !exists {
					debug.DebugLog("Removing orphaned instance for agent %s in session %s", agentName, sessionID)
					delete(session.Instances, agentName)
				} else {
					hasValidInstances = true
				}
			}
		}

		// If no valid instances remain, remove the entire session
		if !hasValidInstances {
			debug.DebugLog("Removing orphaned session: %s", sessionID)
			delete(m.sessions, sessionID)
			if m.activeSession == session {
				m.activeSession = nil
			}
		}
	}
}

// GetWorktreeManager returns the default worktree manager
func (m *Manager) GetWorktreeManager() *git.WorktreeManager {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.worktreeMgr
}

// GetSessionForWorktree returns the session containing an instance with the given worktree (for backward compatibility)
func (m *Manager) GetSessionForWorktree(worktree *git.WorktreeInfo) *Session {
	m.mu.RLock()
	defer m.mu.RUnlock()

	if worktree == nil {
		return nil
	}

	// Search through all sessions for an instance with this worktree path
	for _, session := range m.sessions {
		for _, instance := range session.Instances {
			if instance != nil && instance.Worktree != nil && instance.Worktree.Path == worktree.Path {
				return session
			}
		}
	}
	return nil
}

// GetOrCreateSession is deprecated - creates a new single-agent session (for backward compatibility)
// For new code, use CreateSession instead
func (m *Manager) GetOrCreateSession(worktree *git.WorktreeInfo, agentName string) (*Session, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	// Check if a session exists with an instance using this worktree
	for _, session := range m.sessions {
		for _, instance := range session.Instances {
			if instance != nil && instance.Worktree != nil && instance.Worktree.Path == worktree.Path {
				session.LastAccessed = time.Now()
				debug.DebugLog("Reusing existing session: %s for worktree %s", session.ID, worktree.Path)
				return session, nil
			}
		}
	}

	// Create a new single-agent session
	// Generate a branch name from the worktree
	branchName := worktree.Branch
	if branchName == "" {
		branchName = "unknown"
	}

	// Unlock before calling CreateSession since it will lock
	m.mu.Unlock()
	session, err := m.CreateSession("", branchName, []string{agentName})
	m.mu.Lock()

	return session, err
}
